######################## default configuration ####################
baseURL = "/"
title = "STFIL - Filecoin Liquid Staking"
theme = "copper"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "#" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "STFIL is a Liquid Staking Protocol for Filecoin network. It allows users to obtain block rewards without locking assets and maintaining Storage Provider infrastructure by allowing Storage Providers to obtain more FIL in the protocol pool for pledge."
author = "STFIL"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Preloader
[params.subscription]
enable = false
preloader = "" # use jpg, png, svg or gif format.

############################# social site ########################
[[params.social]]
name = "GitHub"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/stfil-io/"

[[params.social]]
name = "Forum"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://forum.stfil.io/"

[[params.social]]
name = "Twitter"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/stfil_io"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
footer_content = "STFIL is a Liquid Staking Protocol for Filecoin network. It allows users to obtain block rewards without locking assets and maintaining Storage Provider infrastructure by allowing Storage Providers to obtain more FIL in the protocol pool for pledge."
# copyright
copyright = "©2023 STFIL All rights reserved."



############### English navigation ################
# main menu
[[Languages.en.menu.main]]
name = "Protocol"
URL = "/"
weight = 1

#[[Languages.en.menu.main]]
#name = "Governance"
#URL = "about"
#weight = 2

[[Languages.en.menu.main]]
name = "Docs"
URL = "https://docs.stfil.io/"
weight = 3

#[[Languages.en.menu.main]]
#name = "Faq"
#URL = "faq"
#weight = 4

# Footer menu
[[Languages.en.menu.footer]]
name = "Terms & Conditions"
URL = "terms"
weight = 1

[[Languages.en.menu.footer]]
name = "Privacy Policy"
URL = "privacy"
weight = 2

# Footer menu
[[Languages.en.menu.footer_learn]]
name = "Introduction"
URL = "https://docs.stfil.io/docs/development/introduction"
weight = 1

[[Languages.en.menu.footer_learn]]
name = "Guides"
URL = "https://docs.stfil.io/docs/guides/user/staking"
weight = 2

[[Languages.en.menu.footer_learn]]
name = "Developers"
URL = "https://docs.stfil.io/docs/development/smart_contract/staking_pool"
weight = 3

################################### Chinese language #####################################
[Languages.cn]
languageName = "Cn"
languageCode = "zh-CN"
contentDir = "content/chinese"
weight = 1
footer_content = "STFIL 是一个构建在Filecoin上的流动性质押协议，旨在为社区所有、去中心化、无需信任，允许用户在不锁定资产或维护 Storage Provider 基础设施的情况下获得区块奖励。"
# copyright
copyright = "©2023 STFIL All rights reserved."



############### Chinese navigation ################
# main menu
[[Languages.cn.menu.main]]
name = "协议"
URL = "/"
weight = 1

#[[Languages.cn.menu.main]]
#name = "治理"
#URL = "about"
#weight = 2

[[Languages.cn.menu.main]]
name = "文档"
URL = "https://docs.stfil.io/"
weight = 3

#[[Languages.cn.menu.main]]
#name = "常见问题"
#URL = "faq"
#weight = 4

# Footer menu
[[Languages.cn.menu.footer]]
name = "条款和条件"
URL = "terms"
weight = 1

[[Languages.cn.menu.footer]]
name = "隐私权政策"
URL = "privacy"
weight = 2

# Footer menu
[[Languages.cn.menu.footer_learn]]
name = "简介"
URL = "terms-conditions"
weight = 1

[[Languages.cn.menu.footer_learn]]
name = "指南"
URL = "privacy-policy"
weight = 2

[[Languages.cn.menu.footer_learn]]
name = "开发者"
URL = "privacy-policy"
weight = 3
